CREATE TABLE IF NOT EXISTS finished_work (
     id bigint(20) not null auto_increment primary key ,
     documentId varchar(40) not null,
     dbeg datetime,
     stateid int,
     regionid int,
     resname text,
     labname text,
     labcode int,
     resgroup text,
     resgroupCode int,
     subresgroup text,
     subresgroupCode int,
     resmethod text,
     serunit text,
     coeficient double,
     tarcode varchar(50),
     base_rate double,
     seramount int,
     mseramount int,
     subLabName text,
     subLabNameCode text,
     index (dbeg, documentId)
) charset = utf8;